### ISSUE TITLE
feat: find meme source

### ISSUE THREAD

**Issue by lepiaf** [Shad-Z/slack-motd#6]
find meme source

**Comment by cristianemenna** [comment]
**ImgFlip** 
- Doc : https://imgflip.com/api
- **Avantages** :
	- L'API est publique et permet de récupérer l'url d'un meme à partir d'une liste
	- Permet d'ajouter une phrase (voire plusieurs) sur un meme à partir de son id
- **Inconvénients** : 
	- Pas d'endpoint pour récupérer directement un meme de façon random 
	- Nécessite la création d'un compte (gratuit) pour pouvoir générer un meme avec une phrase
	- ~100 memes disponibles

**Comment by cristianemenna** [comment]
**Meme generator**
- Doc : https://rapidapi.com/meme-generator-api-meme-generator-api-default/api/meme-generator
- **Avantages** :
	- Permet d'ajouter deux phrases sur un meme à partir de son nom
	- ~1000 memes disponibles
- **Inconvénients** :
	- Nécessite une API Key pour l'accès à la liste des memes
	- Exige carte bancaire lors de la création du compte gratuit
	- Pas d'endpoint pour récupérer directement un meme de façon random
